name: Grab mini index

on:
  schedule:
    - cron: "5 * * * *"
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: install dep
      run: |
        python -m pip install jsbeautifier
        python -m pip install requests

    - name: Run main.py
      run: python main.py
      
    - name: Update file
      continue-on-error: true
      run: |
        git config --local user.email "victoryqwei@gmail.com"
        git config --local user.name "Victory[bot]"
        git pull origin main
        git add 'gamecode'
        git commit -F temp_commit.txt
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
